serviceTree:
  landscape: &landscape raichu
  cluster: &cluster ruby

tags: &tags
  atomi.cloud/landscape: *landscape
  atomi.cloud/cluster: *cluster

external-secrets:
  podAnnotations:
    <<: *tags
  podLabels:
    <<: *tags

  webhook:
    podLabels:
      <<: *tags
    podAnnotations:
      <<: *tags

  certController:
    podLabels:
      <<: *tags
    podAnnotations:
      <<: *tags

