serviceTree:
  landscape: &landscape entei
  cluster: &cluster topaz

tags: &tags
  atomi.cloud/landscape: *landscape
  atomi.cloud/cluster: *cluster

external-secrets:
  fullnameOverride: cobalt
  podAnnotations:
    <<: *tags
  podLabels:
    <<: *tags

  webhook:
    podLabels:
      <<: *tags
    podAnnotations:
      <<: *tags

  certController:
    podLabels:
      <<: *tags
    podAnnotations:
      <<: *tags

rootToken:
  name: cobalt-secret-operator-infisical
  clientIdKey: CLIENT_ID
  clientSecretKey: CLIENT_SECRET
  type: infisical
  project: sulfoxide-sos
  secretsPath: /
  hostAPI: https://secrets.atomi.cloud