serviceTree:
  landscape: &landscape lapras

tags: &tags
  atomi.cloud/landscape: *landscape

rootToken:
  value: "supersecret"

external-secrets:
  podAnnotations:
    <<: *tags
  podLabels:
    <<: *tags

  webhook:
    podLabels:
      <<: *tags
    podAnnotations:
      <<: *tags

  certController:
    podLabels:
      <<: *tags
    podAnnotations:
      <<: *tags
