{{ if eq .Values.rootToken.type "doppler" }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: "{{ .Values.storeName }}"
  labels: {{- include "sulfoxide-cobalt.labels" . | nindent 4 }}
    atomi.cloud/module: "cluster-store"
  annotations: {{- include "sulfoxide-cobalt.annotations" . | nindent 4 }}
    atomi.cloud/module: "cluster-store"
    helm.sh/hook: post-install,post-upgrade
spec:
  provider:
    doppler:
      auth:
        secretRef:
          dopplerToken:
            name: {{ .Values.rootToken.name }}
            key: {{ .Values.rootToken.key }}
            namespace: {{ .Release.Namespace }}
{{- end }}