{{ if eq .Values.rootToken.type "infisical" }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: "{{ .Values.storeName }}"
  labels: {{- include "sulfoxide-cobalt.labels" . | nindent 4 }}
    atomi.cloud/module: "cluster-store"
  annotations: {{- include "sulfoxide-cobalt.annotations" . | nindent 4 }}
    atomi.cloud/module: "cluster-store"
    helm.sh/hook: post-install,post-upgrade
spec:
  provider:
    infisical:
      auth:
        universalAuthCredentials:
          clientId:
            name: {{ .Values.rootToken.name }}
            key: {{ .Values.rootToken.clientIdKey }}
            namespace: {{ .Release.Namespace }}
          clientSecret:
            name: {{ .Values.rootToken.name }}
            key: {{ .Values.rootToken.clientSecretKey }}
            namespace: {{ .Release.Namespace }}
      secretsScope:
        projectSlug: {{ .Values.rootToken.project}}
        environmentSlug: {{ .Values.serviceTree.landscape }}
        secretsPath: {{ .Values.rootToken.secretsPath }}
      hostAPI: {{ .Values.rootToken.hostAPI }}
{{- end }}