apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sulfoxide-cobalt.fullname" . }}
  labels: {{- include "sulfoxide-cobalt.labels" . | nindent 4 }}
    atomi.cloud/module: "credentials"
  annotations: {{- include "sulfoxide-cobalt.annotations" . | nindent 4 }}
    atomi.cloud/module: "credentials"
type: Opaque
data:
  "{{ .Values.rootToken.key }}": "{{ .Values.rootToken.value | b64enc }}"