{{- if .Values.rootToken.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.rootToken.name }}
  labels: {{- include "sulfoxide-cobalt.labels" . | nindent 4 }}
  annotations: {{- include "sulfoxide-cobalt.annotations" . | nindent 4 }}
type: Opaque
data:
  "{{ .Values.rootToken.key }}": "{{ .Values.rootToken.value | b64enc }}"
{{- end }}


